# Site
repository: ShindongLee/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이신동
title: Software Engineer
email: sdlee9411@gmail.com
email_title: Email
website: https://shindonglee.github.io/cv
website_title: CV

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username: ShindongLee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: lsd.go
linkedin_username: shindong-lee
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "G-7Z7NQT0K0C"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Introduction
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 저는 6년 차 소프트웨어 엔지니어 이신동입니다.
  
  다수의 제품을 출시 후, 수백만 명이 사용하는 서비스로 성장시킨 경험이 있습니다. 
  
  주로 `Kotlin`, `Spring` 으로 서버 개발을 담당했으며, `React`, `Vue.js`를 활용한 간단한 어드민 개발 경험도 있습니다.
  
  저는 함수형 프로그래밍과 객체지향 프로그래밍에 관심이 많습니다.
  
  읽기 쉽고 간결한 코드를 작성하기 위해 노력하며, 테스트하기 좋은 코드가 좋은 코드라고 믿습니다.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: 토스뱅크 외화통장
        link: https://www.tossbank.com/product-service/fx/account
        quote: >
        description: |
          
          2024년 1월에 출시한 토스뱅크 외화통장은 오픈후 약 11개월만에 200만 유저, 1년만에 누적 거래량 20조를 달성했습니다. [[기사 링크]](https://www.smarttoday.co.kr/news/articleView.html?idxno=68112)

          Oracle 을 사용한 원화통장 모놀리틱 시스템과, 분리된 MSA 서버, MySQL 로 구축된 외화통장 사이를 오가는 환전 트랜잭션을, 메시징을 통한 보상 트랜잭션을 통해 구현했습니다.

          기술 스택: Spring, Kotlin, REST, MySQL, Oracle, Redis, Kafka

      - layout: left
        title: 토스뱅크 외환 시스템 구축
        sub_title: 환율 고시, 포지션 커버 등
        quote: >
        description: |
          
          하나은행, J.P. Morgan, 국민은행, 도이치은행 등 외부 파트너 은행과 환율 수신, 주문을 위한 API 연동을 담당했습니다.
          
          이를 통해, 고객들이 외화통장에 사용할 토스뱅크 환율을 최적으로 고시하는 로직을 구현했습니다.
          
          또한, 고객들의 환전과 해외결제로 생기는 포지션을 효율적으로 주문하여 커버하는 로직을 구현했습니다.

          기술 스택: Spring, Kotlin, FIX Protocol, REST, MySQL, Oracle, Redis, Kafka

      - layout: left
        title: 토스뱅크 체크카드
        link: https://www.tossbank.com/product-service/card/check-card
        quote: >
        description: |
          토스뱅크 카드 스쿼드에서 다음과 같은 서비스들을 개발했습니다. 
          - 토스뱅크 체크카드: 770만명
          - 토스뱅크 모임카드: 70만명
          - 토스뱅크 주식캐시백: 38만명
          
          하나의 카드로 다양한 혜택을 선택할 수 있는 시스템을 설계 및 개발하였으며, 개발된 서버는 캐시백 내역을 누적 16억건 이상 처리했습니다.

          기술 스택: Spring, Kotlin, REST, MySQL, Redis, Kafka
          
      - layout: left
        title: 산타토익 (뤼이드 튜터)
        link: https://kr.aitutorsanta.com/
        quote: >
        description: |
          누적 유저 300만을 보유한 구 산타토익을 전면 개편하며 도메인 서버를 개발하였습니다.
          
          새로운 산타토익은 한국, 일본, 미국, 베트남, 대만 총 5개 국가의 유저들의 TOEIC 시험 준비를 돕는 어플리케이션으로 오픈 후 한달 만에 60만명의 유저가 사용했습니다.
          
          기술 스택: Spring, Kotlin, gRPC, PostgreSQL, Redis

      - layout: left
        title: 뤼이드 B2B API
        link: https://www.mk.co.kr/news/business/view/2020/10/1069629
        link_text: 관련 기사 링크
        quote: >
        description: |
          Riiid가 파트너사들에게 인공지능 튜터 서비스를 API 형태로 제공하는 B2B API의 개발 및 운영을 담당했습니다.

          대표적인 파트너사로는 한화 손해보험, 한화 생명보험 등이 있습니다.

          기술 스택: Spring WebFlux, Kotlin, PostgreSQL

      - layout: left
        title: DeepFlow (사내 딥러닝 학습 자동화 플랫폼)
        quote: >
        description: |
          Kakao와 공동체 회사 전 직원이 사용할 수 있는 딥러닝 학습 플랫폼을 개발 및 운영했습니다.
          
          약 200대의 노드 머신, 800개의 GPU를 포함한 대규모 GPU 클러스터를 운영했습니다.
          
          유휴 머신을 관리하고 작업을 할당하는 Resource Manager 서버의 신규 개발을 담당했습니다.

          기술 스택: Python, Flask, Bottle, Go, MySQL, Vue.js, Docker, Mesos, Marathon

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Toss Bank
        link: https://www.tossbank.com/
        sub_title: Server Developer
        caption: 2021.09 - Present
        description: |
          대한민국 3번째 인터넷 은행 토스뱅크에서 서버개발자로 일하고 있습니다.
          
          현재는 외환을 담당하는 FX 스쿼드에서 환전과 해외결제를 개발하고 운영중입니다.
          
          FX 스쿼드는 2023년에 신설되었으며, 스쿼드의 첫번째 개발자로 합류했습니다.

          - 2023.04 - Present: FX 스쿼드
          - 2021.09 - 2023.04: 카드 스쿼드

      - layout: left
        title: Riiid!
        link: https://riiid.com/
        sub_title: Backend Engineer
        caption: 2020.08 - 2021.09
        description: |
          Riiid! Engineering Tribe, Backend Squad의 Backend Engineer로 근무했습니다.

          산타토익(뤼이드 튜터)의 도메인 서버의 개발 및 운영을 담당했습니다.

      - layout: left
        title: Kakao Enterprise
        link: https://www.kakaoenterprise.com
        sub_title: Software Engineer
        caption: 2019.12 - 2020.08
        quote: >
        description: |
           카카오의 AI Lab이 2019년 12월 카카오 엔터프라이즈라는 회사로 독립하였습니다.
                  
           카카오 AI Lab 에서와 동일한 직무를 수행했습니다.

      - layout: left
        title: Kakao
        link: https://www.kakaocorp.com
        sub_title: Software Engineer
        caption: 2019.07 - 2019.12
        quote: >
        description: |
           카카오 AI Lab. 멀티미디어처리파트에서 사내 딥러닝 학습 자동화 서비스를 개발하고 운영했습니다.

  - title: Presentation
    layout: list
    content:
      - layout: left
        title: SLASH 24
        caption: 2024.09
        link: https://www.youtube.com/watch?v=xpwRTu47fqY
        link_text: 발표 영상
        quote: >
        description: |
          토스 기술 컨퍼런스 SLASH 24 에서 `보상 트랜잭션으로 분산 환경에서도 안전하게 환전하기` 라는 제목으로,

          토스뱅크가 모놀리틱 시스템에서 MSA로 전환하는 과도기에서 생겨난 분산 환경에서의 트랜잭션 구현법에 대해 발표했습니다.

  - title: Open Source Contribution
    layout: list
    content:
      - layout: left
        title: Spring Framework
        sub_title: Bug fix
        caption: 2021.05
        link: https://github.com/spring-projects/spring-framework/pull/26857
        link_text: PR 링크
        description: |
          Spring MVC RouterDsl, Spring WebFlux coRouterDsl에서 요청의 앞뒤로 공통의 동작을 정의할 수 있는 filter의 버그를 고쳤습니다.

          관련 내용을 [Riiid 기술 블로그에 게재](https://riiidtechblog.medium.com/spring-webflux-%EC%97%90%EC%84%9C-corouter-filter%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-request-response-%EB%A1%9C%EA%B9%85%ED%95%98%EA%B8%B0-df56f9d9680) 하였습니다.

  - title: Publication
    layout: list
    content:
      - layout: left
        title: CCGAN-VC
        sub_title: ICASSP 2020
        caption: 2020.05
        link: https://arxiv.org/abs/2002.06328
        link_text: arxiv.org/abs/2002.06328
        quote: >
        description: |
          고려대학교 인공지능 연구실에서 다대다 음성변환 프로젝트를 진행했습니다.

          당시 일대일 음성변환 SOTA 모델이었던 CycleGAN-VC를 다대다 음성변환 모델로 확장하였고, 신호 처리 분야 세계 최고 학회인 ICASSP에 1저자로 발표하였습니다.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 고려대학교
        link: www.korea.ac.kr
        sub_title: 컴퓨터학과
        caption: 2014 - 2020
        quote: >
        description: |
          고려대학교 서울캠퍼스 컴퓨터학과에서 컴퓨터학 심화전공으로 학사 학위를 취득했습니다.

  - title: Military Service
    layout: list
    content:
      - layout: left
        title: 551st ICTC
        link: https://www.facebook.com/551stCTC
        link_text: 551st ICTC Facebook
        caption: 2016 - 2017
        sub_title: COMMO (통신/전산병)
        quote: >
        description: |
          551st ICTC에서 KATUSA로 복무했습니다.

  - title: Language Skills
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TOEIC
        caption: May 2019
        quote: >
        description: |
          975

# Footer
footer_show_references: false
# references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme


